config/routes.rb
G0::Application.routes.draw do
  
   match '/plans/edit/:id/content/:content' =>"plans#edit" ,:as=>:plans_edit
   match '/plans/new/plansetting/:id' =>"plans#new" ,:as=>:plans_new_setting
   match '/plans/new/user/:user' =>"plans#new" ,:as=>:plans_new_user
   match '/plans(/index)(/plansetting/:plansetting)(/user/:user)(/system/:system)(/branch/:branch)(/fa/:fa)(/week/:week)(/layout/:layout)(/delete/:delete)(/sort/:sort)' =>"plans#index" ,:as=>:plans_index_fa  #add debug  for delete all
   match '/plans/:id(/layout/:layout)'  =>"plans#show" ,:as=>:plans_show,:via=>:get
  resources :plans
  
  match '/plan_settings/index(/user/:user)(/system/:system)(/week/:week)(/layout/:layout)(/delete/:delete)' =>"plan_settings#index" ,:as=>:plan_settings_index  #add debug  for delete all
  resources :plan_settings
  resources :truck_groups
  
  match '/dingwei/neartruck/:distance/:citycode' =>"dingwei#neartruck" ,:as=>:dingweineartruck
 match '/dingwei/post_gps/:location' =>"dingwei#post_gps" ,:as=>:dingweipost_gps
 match '/dingwei/post_gps(/lat/:lat/lng/:lng)' =>"dingwei#post_gps" ,:as=>:dingweipost_gps
 
  match "/dingwei/userannounce"=>"dingwei#userannounce" ,:as=>:dingweiuserannounce
  match "/dingwei/index"=>"dingwei#index" ,:as=>:dingweiindex
  match '/concerncargos/userconcern'=>"concerncargos#userconcern" ,:as=>:concerncargosuserconcern
  match '/concerncargos/new(/:concern_type)'=>"concerncargos#new" ,:as=>:concerncargosnew
  match '/concerncargos/edit/:id(/:concern_type)'=>"concerncargos#edit" ,:as=>:concerncargosedit
  match '/concerncargos/show/:id(/:concern_type)'=>"concerncargos#show" ,:as=>:concerncargosshow
  resources :concerncargos
  match '/wmails/send_cargo_myself/:id'=>"wmails#send_cargo_myself" ,:as=>:wmailssend_cargo_myself
  match '/wmails/invite_new'=>"wmails#invite_new" ,:as=>:wmailsinvitenew
  resources :wmails
  resources :sitedata
  resources :announces
  
  match '/userlines/city/:city_id'=>"userlines#city" ,:as=>:userlinescity
  match '/userlines/cityto/:city_id'=>"userlines#cityto" ,:as=>:userlinescityto
  match '/userlines/cityfrom/:city_id'=>"userlines#cityfrom" ,:as=>:userlinescityfrom
  match '/userlines/allcity'=>"userlines#allcity" ,:as=>:userlinesallcity
  match '/userlines/myline'  =>'userlines#myline',:as=>:userlinesmyline
  match '/userlines/destroy/:id'  =>'userlines#destroy',:as=>:userlinesdestroy
  resources :userlines

  resources :jubaos

  match '/mail_accounts/index(/:test_mail)'  =>'mail_accounts#index',:as=>:mail_account_index
  match '/mail_accounts/tuiguang((/mode/:mode/way/sent)(/domain/:domain))'  =>'mail_accounts#tuiguang',:as=>:mail_account_tuiguang
  match '/mail_accounts/tuiguang/((/mode/:mode/way/receive)(/domain/:domain))'  =>'mail_accounts#receive',:as=>:mail_account_receive
  resources :mail_accounts
  resources :lib_companies
  resources :feedbacks
  match '/admin/hourscan'  =>'admin#hourscan',:as=>:adminhourscan
  match '/admin/hourscaninfo'  =>'admin#hourscaninfo',:as=>:adminhourscaninfo  
  match '/admin/move'  =>'admin#move',:as=>:adminmove
  match '/admin/moveinfo'  =>'admin#moveinfo',:as=>:adminmoveinfo  
  match '/admin/quzhougrasp'  =>'admin#quzhougrasp',:as=>:adminquzhougrasp
  match '/admin/tf56grasp'  =>'admin#tf56grasp',:as=>:admintf56grasp
  match '/admin/cargo_manage'  =>'admin#cargo_manage',:as=>:admincargo_manage
  match '/admin/stockcargo_manage'  =>'admin#stockcargo_manage' ,:as=>:adminstockcargo_manage
  match '/admin/truck_manage'  =>'admin#truck_manage',:as=>:admintruck_manage
  match '/admin/stocktruck_manage'  =>'admin#stocktruck_manage',:as=>:adminstocktruck_manage
  match '/admin/quote_manage'  =>'admin#quote_manage',:as=>:adminquote_manage
  match '/admin/usercontact_manage'  =>'admin#usercontact_manage',:as=>:adminusercontact_manage
  match '/admin/company_manage'  =>'admin#company_manage' ,:as=>:admincompany_manage
  match '/admin/get_room_contact' =>'admin#get_room_contact' ,:as=>:admin_get_room_contact
  match '/admin/show_room_contact' =>'admin#show_room_contact' ,:as=>:admin_show_room_contact
  match '/admin/grasp_tf56' =>'admin#grasp_tf56' ,:as=>:admin_grasp_tf56
  match '/admin/grasp_quzhou' =>'admin#grasp_quzhou' ,:as=>:admin_grasp_quzhou
  match '/admin/scan' =>'admin#scan' ,:as=>:admin_scan
  match '/admin/scaninfo' =>'admin#scan_info' ,:as=>:admin_scan_info
  match '/admin/show_cron_mail' =>'admin#show_cron_mail' ,:as=>:admin_show_cron_mail
  match 'admin/daily_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#daily_trends' ,:as=>:admin_daily_trends
  match 'admin/hourly_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#hourly_trends' ,:as=>:admin_daily_trends
  match '/admin/request_log_analysis((/all/:all)(/logfile/:logfile))' =>'admin#request_log_analysis' ,:as=>:admin_request_log_analysis
  match '/admin/show_log(/logfile/:logfile)' =>'admin#show_log' ,:as=>:admin_show_log
  match '/admin/backup_db/:code' =>'admin#backup_db' ,:as=>:admin_backup_db
  match '/admin/deploy_test' =>'admin#deploy_test' ,:as=>:admin_deploy_test
  match '/admin/deploy' =>'admin#deploy' ,:as=>:admin_deploy
  match '/admin/send_site_update_to_register(/:test)' =>'admin#send_site_update_to_register' ,:as=>:admin_send_site_update_to_register
  match '/admin/total_truck' =>'admin#total_truck' ,:as=>:admin_total_truck
  match '/admin/concerncargo(/:concern_type)' =>'admin#concerncargo' ,:as=>:admin_concerncargo
  match '/admin/email_list' =>'admin#email_list' ,:as=>:admin_email_list
  match '/admin/sms_list' =>'admin#sms_list' ,:as=>:admin_sms_list
  match '/admin/show_mail' =>'admin#show_mail' ,:as=>:admin_show_mail
  match '/admin/temp_task' =>'admin#temp_task' ,:as=>:admin_temp_task
  match '/admin/allcity'=>'admin#allcity',:as=>:adminallcity

  get "admin/index"
    match '/g00tests(/users(/testname))'=>'g00tests#g00test',:as=>:g00testsg00test
  
  resources :citystatistics

  get "quzhou_wuliu/index"
  get "quzhou_wuliu/show"

  match '/scans/uinfoscan'  =>'scans#uinfoscan',:as=>:scanuinfoscan
  match '/scans/expiretimer'  =>'scans#expiretimer',:as=>:scanexpiretimer
  match '/scans/truckexpire'  =>'scans#truckexpire',:as=>:scantruckexpire
  match '/scans/cargoexpire'  =>'scans#cargoexpire',:as=>:scancargoexpire
  match '/scans/scan'  =>'scans#scan',:as=>:scanscan
  match '/scans/scaninfo'  =>'scans#scaninfo',:as=>:scaninfo
  resources :scans

  resources :lstatistics

  resources :ustatistics

  resources :tstatistics

  resources :cstatistics

 
  
  match '/trucks/quoteinquery/:truck_id' =>'trucks#quoteinquery',:as=>:truckquoteinquery
  match '/cargos/quoteinquery/:cargo_id' =>'cargos#quoteinquery',:as=>:cargoquoteinquery
  match '/trucks/:truck_id/cargos/:cargo_id/inqueries/new'  =>'inqueries#new',:as=>:inquerienew
  match '/trucks/:truck_id/inqueries/truck' =>'inqueries#truck', :as=>:inquerietruck
  match '/cargos/:cargo_id/inqueries/cargo' =>'inqueries#cargo', :as=>:inqueriescargo
  match '/users/:user_id/inqueries/tome/:to' =>'inqueries#index',:as=>:inqueriesto
    match "/cargos/request_chenjiao/:id" =>'cargos#request_chenjiao',:as=>:cargorequest_chenjiao
  match "/trucks/confirm_chenjiao/:id" =>'trucks#confirm_chenjiao',:as=>:trucksconfirm_chenjiao
  resources :inqueries
  match '/cargos/search(/:from/:to(/:page))'  =>'cargos#search',:as=>:cargossearchline
  match '/cargos/:cargo_id/trucks/:truck_id/quotes/new'  =>'quotes#new',:as=>:quotesnew
  match '/cargos/:cargo_id/quotes/cargo' =>'quotes#cargo', :as=>:quotescargo
  match '/trucks/:truck_id/quotes/truck' =>'quotes#truck', :as=>:quotestruck
  match 'users/:user_id/quotes/tome/:to' =>'quotes#index',:as=>:quotesto
 match '/cargos/post_cargo/:cargo' =>'cargos#postcargo',:as=>:postcargo,  :via => :post
 match '/trucks/post_truck/:truck' =>'trucks#posttruck',:as=>:postruck,  :via => :post

  resources :quotes

  resources :line_ads

  match 'searches/:user_id/:stype/' =>'searches#new',:as=>:searchespublicnew

  resources :searches

  get "public_main/index"

  match 'users/login' => 'users#login', :as => :userslogin
  match 'cargos/public' =>'cargos#public',:as=>:cargospublic
  match 'trucks/public' =>'trucks#public',:as=>:truckspublic
  
  
  match '/trucks/city/:city_id(/:citytype)'=>"trucks#city" ,:as=>:truckscity
  match '/trucks/cityto/:city_id'=>"trucks#cityto" ,:as=>:truckscityto
  match '/trucks/cityfrom/:city_id'=>"trucks#cityfrom" ,:as=>:truckscityfrom
  match '/trucks/allcity'=>"trucks#allcity" ,:as=>:trucksallcity

  match '/trucks/search/:from/:to/:page'  =>'trucks#search',:as=>:truckssearchline
  match '/trucks/request_chenjiao/:id' =>"trucks#request_chenjiao" ,:as=>:trucksrequest_chenjiao
  match '/trucks/index/:status' =>"trucks#index" ,:as=>:truckindexstatus
  match  '/trucks/new'=>'trucks#new',:as=>:trucksnew
  match  '/trucks/create'=>'trucks#create',:as=>:truckscreate
  match '/trucks/show' =>'trucks#show',:as=>:trucksshow
  match '/trucks/list/:id'=>'trucks#index',:as=>:trucksindex
  match '/trucks/:truck_id/match' =>'trucks#match', :as=>:trucksmatch
  
    match '/trucks/baojiatruck/:all' =>'trucks#baojiatruck',:as=>:cargobaojiatruck
  resources :trucks do
    resources :inqueries
    resources :quotes
  end
   match '/companies/edit' =>'companies#edit',:as=>:mycompaniesneedit
   match '/companies/yellowpage' =>'companies#yellowpage',:as=>:companiesneyellowpage
    match '/companies/privatecenter' =>'companies#privatecenter',:as=>:companiesneprivatecenter
     match '/companies/publiccenter/:id' =>'companies#publiccenter',:as=>:companiesnepubliccenter
   
  match '/companies/new/(:who)' =>'companies#new',:as=>:companiesnewwho
  match '/companies/index/:id(/:who)' =>'companies#index',:as=>:companiesindex
  match '/companies/showf/:id' =>'companies#showf',:as=>:companiesshowf
  match '/companies/show/:id/(:who)' =>'companies#show',:as=>:companiesshow
  match '/companies/search' =>'companies#search',:as=>:companiessearch
  match '/companies/create' =>'companies#create',:as=>:companiescreate

app/models/userline.rb
class Userline
  include Mongoid::Document
  include Mongoid::Timestamps
  field :user_id, :type => String
  field :fcityid, :type => String
  field :tcityid, :type => String
  field :fcityname, :type => String
  field :tcityname, :type => String
  field :line, :type => String
end

app/helpers/userlines_helper.rb
module UserlinesHelper
  
 def get_province_userlines_from_count(province)
 next_province=province+10000000000
return Userline.where(:fcityid.gte=>province.to_s,:fcityid.lt=> next_province.to_s).count
 end

  def get_province_userlines_to_count(province)
 next_province=province+10000000000
return Userline.where(:tcityid.gte=>province.to_s,:tcityid.lt=> next_province.to_s).count
 end


 def get_region_userlines_from_count(regioncity)
    next_region=regioncity.to_i+100000000
    return Userline.where(:fcityid.gte=>regioncity.to_s,:fcityid.lt=> next_region.to_s).count
 end
 def get_region_userlines_to_count(regioncity)
    next_region=regioncity.to_i+100000000
    return Userline.where(:tcityid.gte=>regioncity.to_s,:tcityid.lt=> next_region.to_s).count
 end
  
end

app/views/userlines/_city_navi.html.erb
 <%#coding:utf-8%>
<%cache("userlines_city_navi") do %>

      <h3>全部专线 共<%=h Userline.count%>条</h3>

    <%$sequnced_province.each do |province|%>
        <ul class="pmenu">

      <a class="citynavi" href="/userlines/city/<%=province%>"> <%=$city_code_name[province.to_s]%>(<%=get_province_userlines_from_count(province)%>-<%=get_province_userlines_to_count(province)%>)</a>
    <%$province_tree[province.to_s].each do |regioncity|%>
      <li class="<%="p#{province}"%>"style="display:none">
 
      <a class="citynavi" href="/userlines/city/<%=regioncity%>">
     <%=$city_code_name[regioncity]%>(<%=get_region_userlines_from_count(regioncity)%>-<%=get_region_userlines_to_count(regioncity)%>) </a>
 
    </li>
    <%end%>

      </ul>
  <%end%>


  


 <%end%>
  

app/views/userlines/_form.html.erb
<%= form_for(@userline) do |f| %>
<fieldset>
  <% if @userline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userline.errors.count, "error") %> prohibited this userline from being saved:</h2>

      <ul>
      <% @userline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id,:value=>session[:user_id] %>

     <span class="lineselector">
  
         
      <a id="from_data_load"  href="/cities/from/<%="100000000000"%>"><%="出发地选择"%></a>
       
      <%= f.hidden_field(:fcityid, { :class => 'fcitycode' }) %>
      <%#= f.hidden_field(:fcity_name,{ :class => 'fcityname' }) %>

    <a  id="to_data_load"  href="/cities/to/<%="100000000000"%>" ><%="到达地选择"%></a>
            <%= f.hidden_field(:tcityid, { :class => 'fcitycode' }) %>
      <%#= f.hidden_field(:tcity_name,{ :class => 'tcityname' }) %>
      <input type="hidden" ></input>
    

    <%= f.submit("创建专线",:class=>"btn primary") %>


  </span>



</fieldset>
<% end %>

app/views/userlines/_form.html_1.erb
<%= form_for(@userline) do |f| %>
  <% if @userline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userline.errors.count, "error") %> prohibited this userline from being saved:</h2>

      <ul>
      <% @userline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :fcityid %><br />
    <%= f.text_field :fcityid %>
  </div>
  <div class="field">
    <%= f.label :tcityid %><br />
    <%= f.text_field :tcityid %>
  </div>
  <div class="field">
    <%= f.label :line %><br />
    <%= f.text_field :line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userlines/_province_navi.html.erb
<%#coding:utf-8%>
<%cache("provinceuserlines") do %>
  <h4>专线 共<%=h Userline.count%></h4>

  <%(0.upto($sequnced_province.size)).select{|x| x % 2==0}.each do |i|%>
    <%province1=$sequnced_province[i]%>
  <%if  province1%>
    <ul>
      <li>
      <a   href="/userlines/city/<%=province1%>"> <%=$city_code_name[province1.to_s]%>(<%=get_province_userlines_from_count(province1)%>-<%=get_province_userlines_to_count(province1)%>)</a>
    </li>
    <li>
      <%if i!=$sequnced_province.size && !$sequnced_province[i+1].blank?%>
        <%province2=$sequnced_province[i+1]%>
        <a   href="/userlines/city/<%=province2%>"> <%=$city_code_name[province2.to_s]%>(<%=get_province_userlines_from_count(province2)%>-<%=get_province_userlines_to_count(province2)%>)</a>
      <%end%>
        </li>
    </ul>
<%end%>
  <%end%>



<%end%>

app/views/userlines/_userline_list.html.erb
<%if  @userlines%>   
  <!--
  <span class="lineselector">
        <a id="from_data_load"  href="/cities/from/<%=@search.fcity_code ||"100000000000"%>"><%=$city_code_name[@search.fcity_code] ||"出发地选择"%></a>
        <input type="hidden" name="userlines[fcitycode]"></input>
        <input type="hidden" ></input>

        <a  id="to_data_load"  href="/cities/to/<%=@search.tcity_code||"100000000000"%>" ><%=$city_code_name[@search.tcity_code] ||"到达地选择"%></a>
        <input type="hidden" name="userlines[tcitycode]"></input>
        <input type="hidden" ></input>
     <input value="专线查询" class="userlines_search" type="submit" name="zhuanianchaxun" style="background-color:#F2F2F2;"></input>

    </span>
  -->
  <table class="table table-striped">
    <tr>
      <th>专线城市</th>
      <th>专线城市</th>
      <th>发布人</th>
      <th>联系电话</th>
      <th>发布公司</th>
      <th>发布日期</th>
    </tr>

    <% @userlines.each do |userline| %>
       <%user=User.where(:_id=>userline.user_id).first%>
        <%unless user.blank?%>
      <tr>
        
        <%if userline.fcityname.blank?%>
          <%userline.update_attribute(:fcityname,get_city_full_name(userline.fcityid))%>
        <%end%>
        <%if userline.tcityname.blank?%>
          <%userline.update_attribute(:tcityname,get_city_full_name(userline.tcityid))%>
        <%end%>

        <td><%= userline.fcityname %></td>
        <td><%= userline.tcityname %></td>
         
        <td><%= user.name %></td>
        <td><%= user.mobilephone %></td>        
        <%if user.company_id%>
          <%company=Company.where(:user_name=>user.name).first%>
          <td><a  target="_blank"  href="/companies/show/<%=company.id%>"><%= company.name %></a></td>        
        <%else%>
          <td><%="个人" %></td>
        <%end%>
        <td><%= userline.created_at.to_s.slice(0,19) %></td>
      </tr>
      <%end%>
    <% end %>
  </table>
  <%= will_paginate @userlines ,:previous_label=>"上一页",:next_label=>"下一页"%>
<%else%>
  <p> 没有找对对应专线.</p>
<%end%>
<br />

app/views/userlines/cityfrom.html.erb
<%#= render '/searches/cform' %>
 <%#= cache(:action=>"search", :layout=>nil,:action_suffix =>"cargo#{@action_suffix}") do %>

<%=render '/userlines/userline_list'%>

<%#=end%>

app/views/userlines/cityto.html.erb
<%#= render '/searches/cform' %>
 <%#= cache(:action=>"search", :layout=>nil,:action_suffix =>"cargo#{@action_suffix}") do %>
<%=render '/userlines/userline_list'%>

<%#=end%>

app/views/userlines/createfail.html.erb
<p id="notice"><%= notice %></p>

<%unless @can_create%>
<p>目前不能创建超过10条专线.</p>
<%end%>
<%if @wrong_city==true%>
<p>城市选择错误.</p>
<%else%>
<p>创建失败.</p>
<%end%>

app/views/userlines/createsucc.html.erb
<p id="notice"><%= notice %></p>

<p>
成功创建专线.
</p>

<%= link_to '添加新的专线', new_userline_path %>

app/views/userlines/edit.html.erb
<h1>Editing userline</h1>

<%= render 'form' %>

<%= link_to 'Show', @userline %> |
<%= link_to 'Back', userlines_path %>

app/views/userlines/index.html.erb
<%cache "userlines_all" do%>
<%=render '/userlines/userline_list'%>
<%end%>

app/views/userlines/myline.html.erb
<%if  @userlines%>   

<table class="table table-striped">
  <tr>

    <th>专线城市</th>
    <th>专线城市</th>
    <th>发布日期</th>
     <th>管理</th>
  </tr>

<% @userlines.each do |userline| %>
  <tr>

    <td><%= userline.fcityname %></td>
    <td><%= userline.tcityname %></td>
    <td><%= userline.created_at %></td>

    <td><a class="btn btn-default" href="/userlines/destroy/<%=userline.id%>">删除</a></td>
  </tr>
<% end %>
</table>
<%else%>
<p> 没有找对对应专线.</p>
<%end%>
<br />



<%= link_to '添加新的专线', new_userline_path %>

app/views/userlines/new.html.erb
<h3>新建物流专线</h3>

<%= render 'form' %>

<p>注意:目前每个用户最多只能建10条专线,已创建(<%=Userline.where(:user_id=>session[:user_id]).count%>)</p>
<%#= link_to 'Back', userlines_path %>

app/views/userlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @userline.user_id %>
</p>

<p>
  <b>Fcityid:</b>
  <%= @userline.fcityid %>
</p>

<p>
  <b>Tcityid:</b>
  <%= @userline.tcityid %>
</p>

<p>
  <b>Line:</b>
  <%= @userline.line %>
</p>


<%= link_to 'Edit', edit_userline_path(@userline) %> |
<%= link_to 'Back', userlines_path %>