config/routes.rb
G0::Application.routes.draw do
  
   match '/plans/edit/:id/content/:content' =>"plans#edit" ,:as=>:plans_edit
   match '/plans/new/plansetting/:id' =>"plans#new" ,:as=>:plans_new_setting
   match '/plans/new/user/:user' =>"plans#new" ,:as=>:plans_new_user
   match '/plans(/index)(/plansetting/:plansetting)(/user/:user)(/system/:system)(/branch/:branch)(/fa/:fa)(/week/:week)(/layout/:layout)(/delete/:delete)(/sort/:sort)' =>"plans#index" ,:as=>:plans_index_fa  #add debug  for delete all
   match '/plans/:id(/layout/:layout)'  =>"plans#show" ,:as=>:plans_show,:via=>:get
  resources :plans
  
  match '/plan_settings/index(/user/:user)(/system/:system)(/week/:week)(/layout/:layout)(/delete/:delete)' =>"plan_settings#index" ,:as=>:plan_settings_index  #add debug  for delete all
  resources :plan_settings
  resources :truck_groups
  
  match '/dingwei/neartruck/:distance/:citycode' =>"dingwei#neartruck" ,:as=>:dingweineartruck
 match '/dingwei/post_gps/:location' =>"dingwei#post_gps" ,:as=>:dingweipost_gps
 match '/dingwei/post_gps(/lat/:lat/lng/:lng)' =>"dingwei#post_gps" ,:as=>:dingweipost_gps
 
  match "/dingwei/userannounce"=>"dingwei#userannounce" ,:as=>:dingweiuserannounce
  match "/dingwei/index"=>"dingwei#index" ,:as=>:dingweiindex
  match '/concerncargos/userconcern'=>"concerncargos#userconcern" ,:as=>:concerncargosuserconcern
  match '/concerncargos/new(/:concern_type)'=>"concerncargos#new" ,:as=>:concerncargosnew
  match '/concerncargos/edit/:id(/:concern_type)'=>"concerncargos#edit" ,:as=>:concerncargosedit
  match '/concerncargos/show/:id(/:concern_type)'=>"concerncargos#show" ,:as=>:concerncargosshow
  resources :concerncargos
  match '/wmails/send_cargo_myself/:id'=>"wmails#send_cargo_myself" ,:as=>:wmailssend_cargo_myself
  match '/wmails/invite_new'=>"wmails#invite_new" ,:as=>:wmailsinvitenew
  resources :wmails
  resources :sitedata
  resources :announces
  
  match '/userlines/city/:city_id'=>"userlines#city" ,:as=>:userlinescity
  match '/userlines/cityto/:city_id'=>"userlines#cityto" ,:as=>:userlinescityto
  match '/userlines/cityfrom/:city_id'=>"userlines#cityfrom" ,:as=>:userlinescityfrom
  match '/userlines/allcity'=>"userlines#allcity" ,:as=>:userlinesallcity
  match '/userlines/myline'  =>'userlines#myline',:as=>:userlinesmyline
  match '/userlines/destroy/:id'  =>'userlines#destroy',:as=>:userlinesdestroy
  resources :userlines

  resources :jubaos

  match '/mail_accounts/index(/:test_mail)'  =>'mail_accounts#index',:as=>:mail_account_index
  match '/mail_accounts/tuiguang((/mode/:mode/way/sent)(/domain/:domain))'  =>'mail_accounts#tuiguang',:as=>:mail_account_tuiguang
  match '/mail_accounts/tuiguang/((/mode/:mode/way/receive)(/domain/:domain))'  =>'mail_accounts#receive',:as=>:mail_account_receive
  resources :mail_accounts
  resources :lib_companies
  resources :feedbacks
  match '/admin/hourscan'  =>'admin#hourscan',:as=>:adminhourscan
  match '/admin/hourscaninfo'  =>'admin#hourscaninfo',:as=>:adminhourscaninfo  
  match '/admin/move'  =>'admin#move',:as=>:adminmove
  match '/admin/moveinfo'  =>'admin#moveinfo',:as=>:adminmoveinfo  
  match '/admin/quzhougrasp'  =>'admin#quzhougrasp',:as=>:adminquzhougrasp
  match '/admin/tf56grasp'  =>'admin#tf56grasp',:as=>:admintf56grasp
  match '/admin/cargo_manage'  =>'admin#cargo_manage',:as=>:admincargo_manage
  match '/admin/stockcargo_manage'  =>'admin#stockcargo_manage' ,:as=>:adminstockcargo_manage
  match '/admin/truck_manage'  =>'admin#truck_manage',:as=>:admintruck_manage
  match '/admin/stocktruck_manage'  =>'admin#stocktruck_manage',:as=>:adminstocktruck_manage
  match '/admin/quote_manage'  =>'admin#quote_manage',:as=>:adminquote_manage
  match '/admin/usercontact_manage'  =>'admin#usercontact_manage',:as=>:adminusercontact_manage
  match '/admin/company_manage'  =>'admin#company_manage' ,:as=>:admincompany_manage
  match '/admin/get_room_contact' =>'admin#get_room_contact' ,:as=>:admin_get_room_contact
  match '/admin/show_room_contact' =>'admin#show_room_contact' ,:as=>:admin_show_room_contact
  match '/admin/grasp_tf56' =>'admin#grasp_tf56' ,:as=>:admin_grasp_tf56
  match '/admin/grasp_quzhou' =>'admin#grasp_quzhou' ,:as=>:admin_grasp_quzhou
  match '/admin/scan' =>'admin#scan' ,:as=>:admin_scan
  match '/admin/scaninfo' =>'admin#scan_info' ,:as=>:admin_scan_info
  match '/admin/show_cron_mail' =>'admin#show_cron_mail' ,:as=>:admin_show_cron_mail
  match 'admin/daily_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#daily_trends' ,:as=>:admin_daily_trends
  match 'admin/hourly_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#hourly_trends' ,:as=>:admin_daily_trends
  match '/admin/request_log_analysis((/all/:all)(/logfile/:logfile))' =>'admin#request_log_analysis' ,:as=>:admin_request_log_analysis
  match '/admin/show_log(/logfile/:logfile)' =>'admin#show_log' ,:as=>:admin_show_log
  match '/admin/backup_db/:code' =>'admin#backup_db' ,:as=>:admin_backup_db
  match '/admin/deploy_test' =>'admin#deploy_test' ,:as=>:admin_deploy_test
  match '/admin/deploy' =>'admin#deploy' ,:as=>:admin_deploy
  match '/admin/send_site_update_to_register(/:test)' =>'admin#send_site_update_to_register' ,:as=>:admin_send_site_update_to_register
  match '/admin/total_truck' =>'admin#total_truck' ,:as=>:admin_total_truck
  match '/admin/concerncargo(/:concern_type)' =>'admin#concerncargo' ,:as=>:admin_concerncargo
  match '/admin/email_list' =>'admin#email_list' ,:as=>:admin_email_list
  match '/admin/sms_list' =>'admin#sms_list' ,:as=>:admin_sms_list
  match '/admin/show_mail' =>'admin#show_mail' ,:as=>:admin_show_mail
  match '/admin/temp_task' =>'admin#temp_task' ,:as=>:admin_temp_task
  match '/admin/allcity'=>'admin#allcity',:as=>:adminallcity

  get "admin/index"
    match '/g00tests(/users(/testname))'=>'g00tests#g00test',:as=>:g00testsg00test
  
  resources :citystatistics

  get "quzhou_wuliu/index"
  get "quzhou_wuliu/show"

  match '/scans/uinfoscan'  =>'scans#uinfoscan',:as=>:scanuinfoscan
  match '/scans/expiretimer'  =>'scans#expiretimer',:as=>:scanexpiretimer
  match '/scans/truckexpire'  =>'scans#truckexpire',:as=>:scantruckexpire
  match '/scans/cargoexpire'  =>'scans#cargoexpire',:as=>:scancargoexpire
  match '/scans/scan'  =>'scans#scan',:as=>:scanscan
  match '/scans/scaninfo'  =>'scans#scaninfo',:as=>:scaninfo
  resources :scans

  resources :lstatistics

  resources :ustatistics

  resources :tstatistics

  resources :cstatistics

 
  
  match '/trucks/quoteinquery/:truck_id' =>'trucks#quoteinquery',:as=>:truckquoteinquery
  match '/cargos/quoteinquery/:cargo_id' =>'cargos#quoteinquery',:as=>:cargoquoteinquery
  match '/trucks/:truck_id/cargos/:cargo_id/inqueries/new'  =>'inqueries#new',:as=>:inquerienew
  match '/trucks/:truck_id/inqueries/truck' =>'inqueries#truck', :as=>:inquerietruck
  match '/cargos/:cargo_id/inqueries/cargo' =>'inqueries#cargo', :as=>:inqueriescargo
  match '/users/:user_id/inqueries/tome/:to' =>'inqueries#index',:as=>:inqueriesto
    match "/cargos/request_chenjiao/:id" =>'cargos#request_chenjiao',:as=>:cargorequest_chenjiao
  match "/trucks/confirm_chenjiao/:id" =>'trucks#confirm_chenjiao',:as=>:trucksconfirm_chenjiao
  resources :inqueries
  match '/cargos/search(/:from/:to(/:page))'  =>'cargos#search',:as=>:cargossearchline
  match '/cargos/:cargo_id/trucks/:truck_id/quotes/new'  =>'quotes#new',:as=>:quotesnew
  match '/cargos/:cargo_id/quotes/cargo' =>'quotes#cargo', :as=>:quotescargo
  match '/trucks/:truck_id/quotes/truck' =>'quotes#truck', :as=>:quotestruck
  match 'users/:user_id/quotes/tome/:to' =>'quotes#index',:as=>:quotesto
 match '/cargos/post_cargo/:cargo' =>'cargos#postcargo',:as=>:postcargo,  :via => :post
 match '/trucks/post_truck/:truck' =>'trucks#posttruck',:as=>:postruck,  :via => :post

  resources :quotes

  resources :line_ads

  match 'searches/:user_id/:stype/' =>'searches#new',:as=>:searchespublicnew

  resources :searches

  get "public_main/index"

  match 'users/login' => 'users#login', :as => :userslogin
  match 'cargos/public' =>'cargos#public',:as=>:cargospublic
  match 'trucks/public' =>'trucks#public',:as=>:truckspublic
  
  
  match '/trucks/city/:city_id(/:citytype)'=>"trucks#city" ,:as=>:truckscity
  match '/trucks/cityto/:city_id'=>"trucks#cityto" ,:as=>:truckscityto
  match '/trucks/cityfrom/:city_id'=>"trucks#cityfrom" ,:as=>:truckscityfrom
  match '/trucks/allcity'=>"trucks#allcity" ,:as=>:trucksallcity

  match '/trucks/search/:from/:to/:page'  =>'trucks#search',:as=>:truckssearchline
  match '/trucks/request_chenjiao/:id' =>"trucks#request_chenjiao" ,:as=>:trucksrequest_chenjiao
  match '/trucks/index/:status' =>"trucks#index" ,:as=>:truckindexstatus
  match  '/trucks/new'=>'trucks#new',:as=>:trucksnew
  match  '/trucks/create'=>'trucks#create',:as=>:truckscreate
  match '/trucks/show' =>'trucks#show',:as=>:trucksshow
  match '/trucks/list/:id'=>'trucks#index',:as=>:trucksindex
  match '/trucks/:truck_id/match' =>'trucks#match', :as=>:trucksmatch
  
    match '/trucks/baojiatruck/:all' =>'trucks#baojiatruck',:as=>:cargobaojiatruck
  resources :trucks do
    resources :inqueries
    resources :quotes
  end
   match '/companies/edit' =>'companies#edit',:as=>:mycompaniesneedit
   match '/companies/yellowpage' =>'companies#yellowpage',:as=>:companiesneyellowpage
    match '/companies/privatecenter' =>'companies#privatecenter',:as=>:companiesneprivatecenter
     match '/companies/publiccenter/:id' =>'companies#publiccenter',:as=>:companiesnepubliccenter
   
  match '/companies/new/(:who)' =>'companies#new',:as=>:companiesnewwho
  match '/companies/index/:id(/:who)' =>'companies#index',:as=>:companiesindex
  match '/companies/showf/:id' =>'companies#showf',:as=>:companiesshowf
  match '/companies/show/:id/(:who)' =>'companies#show',:as=>:companiesshow
  match '/companies/search' =>'companies#search',:as=>:companiessearch
  match '/companies/create' =>'companies#create',:as=>:companiescreate

app/models/plan.rb
class Plan
  include Mongoid::Document
  include Mongoid::Timestamps
  field :plansetting, :type => String
  field :user, :type => String
  field :system, :type => String
  field :branch, :type => String
  field :fa, :type => String
  field :title, :type => String
  field :tag , :type => String
  field :plan, :type => String
  field :procedure, :type => String
  field :summary, :type => String
  field :phase, :type => String
  field :deliver, :type => String
  field :comments, :type => String
  field :status, :type => String
  field :review, :type => String
  field :check, :type => Boolean
  field :plantype, :type => String
  field :priority,:type=>Integer
end

app/controllers/plans_controller.rb
#coding:utf-8
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json
  include PlansHelper
  include_kindeditor :only => [:new, :edit]
  before_filter:admin_authorize
  layout "plan"
  def index
    init_plan
    search_critial= Hash.new
    search_critial[:user]=params[:user] if  params[:user]
    search_critial[:system]=params[:system] if  params[:system]
    search_critial[:plansetting]=params[:plansetting] if  params[:plansetting]
    search_critial[:branch]=params[:branch] if  params[:branch]
    search_critial[:fa]=params[:fa] if  params[:fa]
    search_critial[:created_at.gte]=Time.now.ago(86400*params[:week].to_i) if  params[:week] 
     @url=request.url
    if params[:sort]==nil
    params[:sort]="priority" 
    else
      @url=@url.gsub("/sort/#{params[:sort]}","").to_s
    end


    if search_critial.size>0      
      # puts "search critial=#{search_critial}"
      #  @plans = Plan.where(search_critial).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>50)
      @plans = Plan.where(search_critial).desc(params[:sort]).paginate(:page=>params[:page]||1,:per_page=>50)
    else
      #  puts "no      search critial"
      #  @plans = Plan.all.desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>50)
      @plans = Plan.all.desc(params[:sort]).paginate(:page=>params[:page]||1,:per_page=>50)
    end

    respond_to do |format|
      if params[:layout]
        format.html {render :layout=>nil}# index.html.erb
      else
        format.html # index.html.erb
      end
   
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if params[:layout]
        format.html{ render :layout=>nil} # show.html.erb
      else
        format.html # show.html.erb
   
      end
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    if params[:id]
      @plan_setting=PlanSetting.find(params[:id])
    end

    @plan = Plan.new
    puts "@plan_setting.id=#{@plan_setting.id}"
    @plan.update_attributes(:system=>@plan_setting.system,:branch=>@plan_setting.branch,:fa=>@plan_setting.fa,:plansetting=>@plan_setting.id)
    
    respond_to do |format|
      format.html { redirect_to :action=>"edit",:id=>@plan.id,notice: 'Plan was successfully created.' }
      format.json { render json: @plan }
    end
  end
  # GET /plans/1/edit
  def edit
    init_plan    
    @plan = Plan.find(params[:id]) 

    puts "flash notice=#{flash[:notice]}"
  end
  

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])
    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])
    @plan_setting=PlanSetting.find(@plan.plansetting)
    init_plan   
    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        unless @plan_setting.contributor.include?(@plan.user)
          @plan_setting.add_to_set(:contributor,@plan.user)
        end
        #  format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        flash[:notice]="Plan更新成功在-#{Time.now.to_s.slice(0,19)}"
        if params[:content].size>0
          format.html { redirect_to action: "edit" ,:content=>params[:content],:flash=>{:notice=>flash[:notice]}}
        else
          format.html { redirect_to action: "edit" ,:flash=>{:notice=>flash[:notice]}}
        end
        format.json { head :no_content }
      else
        flash[:notice]="Plan更新失败"
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
  
  def init_plan
    @phase=[["operating","operating"],["brainstorm","brainstorm"],["study","study"],["requirement","requirement"],["design","design"],["prototype","prototype"],
    ["refactor","refactor"],["test","test"],["deploy","deploy"],["notes","notes"],["others","others"]]
    @delivers=[["plan-do-check","plan-do-check"],["code","code"],["code-doc","code-doc"],["offline-doc","offline-doc"]]
    @plan_users=[["hunter","hunter"],["steven","steven"]]
  end

end

app/views/plans/_edit_navi.html.erb
<p>  
  <a <%="style= display:inline-block;width:100px;background:#fad2b5;" if params[:content]=="plan"%> href="/plans/edit/<%=@plan.id%>/content/plan" >Plan</a>
  <a <%="style= display:inline-block;width:100px;background:#fad2b5;" if params[:content]=="do"%> href="/plans/edit/<%=@plan.id%>/content/do" >Do</a>
  <a <%="style= display:inline-block;width:100px;background:#fad2b5;" if params[:content]=="summary"%> href="/plans/edit/<%=@plan.id%>/content/summary" >Summary</a>  
  <a <%="style= display:inline-block;width:100px;background:#fad2b5;" if params[:content]=="comments"%> href="/plans/edit/<%=@plan.id%>/content/comments" >Comments</a>
  <a href="/plan_settings">返回全部计划设置</a>
  <a href="/plans">返回全部计划管理</a>
  <a href="/plans/index/system/<%=@plan.system%>/fa/<%=@plan.fa%>">返回该FA的计划管理</a>
</p>

app/views/plans/_list.html.erb
<table class="table table-striped">
  <tr>
    <th><a href="<%=@url+"/sort/user"%>">User</a></th>
   <th><a href="<%=@url+"/sort/fa"%>">FA</a></th>
    <th>Title</th>
    <th>浮动查看</th>
    <th>SystemB</th>
    <th><a href="<%=@url+"/sort/priority"%>">Priority</a></th>
    <th>Size</th>
    <th>Plan</th>
    <th>Do</th> 
    <th>Summary</th>   
    <th>Comments</th>
    <th>Deliver</th>

    <th><a href="<%=@url+"/sort/status"%>">Status</a></th>
        <th><a href="<%=@url+"/sort/updated_at"%>">更新于</a></th>

    <!-- <th>Review</th>
     <th>Check</th>-->

    <th></th>
    <th></th>
  </tr>
<%total_size=0%>
  <% @plans.each do |plan| %>
    <tr>
      <td><a href="/plans/index/user/<%=plan.user%>"><%= plan.user %></a></td>
      <td><a href="/plans/index/system/<%=plan.system%>/fa/<%=plan.fa%>"><%= plan.fa %></a></td>
      <td><%= plan.title %></td>
         <td><%= link_to '查看', plan,:class =>"plan_show"  %></td>
      <td><a href="/plans/index/system/<%=plan.system%>"><%= plan.system %></a>-<a href="/plans/index/system/<%=plan.system%>/branch/<%=plan.branch%>"><%= plan.branch %></a></td>
      <td><%= plan.priority %></td></td>
      <%plan_size=(plan.plan||"").size+(plan.procedure||"").size+(plan.summary||"").size+(plan.comments||"").size %>
      <%total_size+=plan_size%>
      <td><%= plan_size%></td></td>
      <td>
        <a href="/plans/edit/<%=plan.id%>/content/plan" >Plan</a>
      </td>

      <td>
        <a href="/plans/edit/<%=plan.id%>/content/do" >Do</a>  </td>
      <td> <a href="/plans/edit/<%=plan.id%>/content/summary" >Summary</a>  </td></td>

      <td><a href="/plans/edit/<%=plan.id%>/content/comments" >Comments</a> </td>
      <td><%= plan.deliver %></td>
      <td><%= plan.status %></td>
      <%day=((Time.now-plan.updated_at)/86400).to_i%>
      
      <%if day==0%>
      <%hour=((Time.now-plan.updated_at)/3600).to_i%>
      <%if hour==0%>
       <td <%="style=background:#fae5c9;" %>>更新于<%=((Time.now-plan.updated_at)/60).to_i%>分钟前</td>
      <%else%>
         <td <%="style=background:#fae5c9;" %>>更新于<%=hour%>小时前</td>
         <%end%>
      <%elsif day <3 %>
        <td <%="style=background:#fae5c9;" %>>更新于<%=day%>天前</td>
      <%elsif (day>3 && day<15) %>
        <td <%="style=background:#fbc276;" %>>更新于<%=day%>天前</td>
      <%else%>
        <td <%="style=background:#f7a536;" %>>更新于<%=day%>天前</td>
      <%end%>

      <!--
      <td><%= plan.review %></td>
      <td><%= plan.check %></td>-->
   
      <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
      <%if params[:delete]%>
        <td><%=  button_to 'Destroy', plan, confirm: 'Are you sure?', method: :delete %></td>
      <%end%>
    </tr>
  <% end %>
</table>
<p>Total Plan size=<%=total_size%></p>

<%= will_paginate @plans ,:previous_label=>"上一页",:next_label=>"下一页"%>

app/views/plans/_navi.html.erb
<table >
    <tr>
  <td> </td>
  

  <%["W090","Android","Caiji","KD090"] .each do |system|%>
  <td style="width:120px;"> <a  href="/plans/index/system/<%=system%>"><%=system%>(<%=Plan.where(:system=>system).count%>)</a>---<a href="/plan_settings/index/system/<%=system%>">返回</a></td>
  <%end%>
   
  </tr>

  <%@plan_users.each do |user|%>
    <tr>
      <td><strong>
      <%=user[0]%>区:</strong></td>      
      <td> <a  href="/plans/index/user/<%=user[0]%>/week/1">本周计划(<%=Plan.where(:user=>user[0],:created_at.gte=>Time.now.ago(86400*7)).count%>)</a></td>
      <td>  <a  href="/plans/index/user/<%=user[0]%>/week/1">两周计划(<%=Plan.where(:user=>user[0],:created_at.gte=>Time.now.ago(86400*14)).count%>)</a></td>
      <td>  <a  href="/plans/index/user/<%=user[0]%>/week/4">一月计划(<%=Plan.where(:user=>user[0],:created_at.gte=>Time.now.ago(86400*30)).count%>)</a></td>
       <td><a  href="/plans/index/user/<%=user[0]%>">全部计划(<%=Plan.where(:user=>user[0]).count%>)</a></td>
       
    </tr>
  <%end%>

</table>


<br />

<%#= link_to 'New Plan', new_plan_path %>

app/views/plans/_plannavi.html.erb
<%user=User.find(session[:user_id]) unless session[:user_id].nil?%>
<ul>
    <li><a  href="/admin/">网站管理</a></li>

    <h4>W090-最近一月</h4> 
    <%Plan.where(:system=>"W090").where(:created_at.gte=>Time.now.ago(86400*30)).desc(:updated_at).each do |plan|%>
    <li > <a style="margin:0px;padding: 0px;" href="/plans/index/system/<%=plan.system%>/fa/<%=plan.fa%>"><strong><%=plan.fa%></a></strong><a style="width: 350px;display:inline-block;" href="/plans/edit/<%=plan.id%>"><%=(plan.title||"").slice(0,19)%></a><li>
    <%end%>
      
   <h4>Android-最近一月</h4> 
    <%Plan.where(:system=>"Android").where(:created_at.gte=>Time.now.ago(86400*30)).desc(:updated_at).each do |plan|%>
    <li ><a style="margin:0px;padding: 0px;" href="/plans/index/system/<%=plan.system%>/fa/<%=plan.fa%>"><strong><%=plan.fa%></a></strong><a style="width: 350px;display:inline-block;" href="/plans/edit/<%=plan.id%>"><%=(plan.title||"").slice(0,19)%></a><li>
    <%end%>
    <h4>开发管理</h4>
    <li><a href="/plan_settings">新建计划</a><li>
     <li><a href="/plans">全部计划</a><li>
</ul>

app/views/plans/edit.html.erb
<strong>Plan <%=@plan.fa%>区</strong>
<span><%=@plan.system%>-<%=@plan.branch%>分支区</span>
<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<%=render"plans/navi"%>

<%=render"plans/list"%>

<br />

<a  class="btn btn-dark" href="/plans/index/delete/true">Delete Manage</a>
<%planhelp=Plan.where(:user=>"hunter","fa"=>"计划管理").first%>
<%if planhelp %>
<a href="/plans/<%=planhelp.id%>">计划管理使用帮助</a>
<%end%>
<%#= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h2>我最近计划</h2>
<%=render"plans/list"%>
<h1><%=params[:user]%> New plan Item</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>
<div style="min-width: 600px;">
<p>
   <%= @plan.fa %>
  作者：<%= @plan.user %> 


</p>

<h2>  <%= @plan.title %></h2>
 

<p>
  <h3>Plan:</h3>
  <%= raw(@plan.plan) %>
</p>

<p>
  <p>
  <h3>procedure:</h3>
  <%=raw(@plan.procedure)%>
</p>
<p>
  <h3>summary:</h3>
  <%= raw(@plan.summary) %>
</p>

<p>
  <h3>Comments:</h3>
  <%= raw(@plan.comments) %>
</p>

<p>
  <b>Status:</b>
  <%= @plan.status %>
</p>
<p>

  <b>Deliver:</b>
  <%= @plan.deliver %>
</p>
<p>
  <b>Review:</b>
  <%= @plan.review %>
</p>




<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>
</div>